services:
  n8ndb:
    image: postgres:17
    user: "1000:1000"
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=UstawJakiesTrudneHaslo
      - POSTGRES_DB=n8n
    volumes:
      - /docker/n8n/postgres_data:/var/lib/postgresql/data
  n8n:
    image: n8nio/n8n
    restart: always
    user: "1000:1000"
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8ndb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=UstawJakiesTrudneHaslo
      - NODE_ENV=production
      - WEBHOOK_URL=https://twoja.domena.pl
      - N8N_HOST=twoja.domena.pl
      - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=false
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Europe/Warsaw
    depends_on:
      - n8ndb
    volumes:
      - /docker/n8n/n8ndata:/home/node/.n8n
      
